require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 3.0
  Include:
    - bin/*
    - lib/**/*.rb
    - test/*.rb
    - '*.gemspec'
    - Rakefile
    - .simplecov
  Exclude:
    - vendor/**/*
    - pkg/**/*

Style/Copyright:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Lint/SymbolConversion:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - test/*.rb
    - '*.gemspec'

Layout/LineLength:
  Exclude:
    - test/*.rb

Naming/FileName:
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
