AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 2.4

Style/Copyright:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Rails:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - test/*.rb
    - '*.gemspec'

Metrics/LineLength:
  Exclude:
    - test/*.rb
