AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 2.4

Style/Copyright:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false
