require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 2.7
  Include:
    - bin/*
    - lib/**/*.rb
    - test/*.rb
    - '*.gemspec'
    - Rakefile
    - .simplecov

Style/Copyright:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - test/*.rb
    - '*.gemspec'

Layout/LineLength:
  Exclude:
    - test/*.rb

Naming/FileName:
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
