language: ruby
cache: bundler
sudo: false

env:
  - secure: "f2nLlqvTl6+wQ/gEdEAcrkw8JfH3LiiLDJLlWHkcrTFBjCT68tFHlIxl6DnfcpQp2wE5Fzm9Rx0YSYv3xUUDlcvIWRK27aA8E+Wu9nmqIPMUUYL0Qls5WgqGLyhCH//WfIp0VabML0uyz1Pd82Ax9Jo1oJCdSdpvp2yeSRXDzGheRj00U7Y472dpGu2P1nyvZEgL4bwwMzRnnMNFI5QnbmgAOHnWBNQA2mgZ3LR68lYZfmPSupSrqcqvHe1J9Avur6Kh5MQGl8Y69l8BNSzNnilmBWRWJjLd5wyb/nAFuSaxjEwbUuKHAdNLny6l3IKZ+Dm0kxtdaZsATujCZBttSoajGjzAMu+jVqoBtbRj6+bH5auDjjMX8o+pTloCacW4W69/q7MdmRujdJwbucjrpu/H+NgNKM7PAjBf7CM87M1BRwnFf5d6hwgvbEEP6lgY5++VWnVTYnkBQ5MRleiyaQYq41BmL5VAwZxdpfxJghJEsdJYlzb5Q6whZY+64ATGAzuY/UzKVFRUE6xckKhQhoYJe97rkGKLS+VITjG6h6gSpKfcun0rFeExUmzlCZcOSeeyXx/rchEYJcAEQqjiLEnAAY0DTpSlUDnxdHwlyJx/lVLpkMoxowRnyBWL8h1qS/IEhWe9rtgJ3UFzgSt/vsO8p25Jj6GhPpERuMWVIB8="

rvm:
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install
script:
  - bundle exec rake rdoc
  - bundle exec rake test
  - bundle exec rake gem

before_deploy:
  - bundle exec rake ronn
deploy:
  provider: rubygems
  gem: filmrolls
  api_key:
    secure: "YLXWVcWEprun62JzvDOH9ExWNIjHCprpb0UJ4h1rNUOgqGKfFfd2z4t70iySssn3jL+/F/ywObfHMc7ElmxCgPM9plCP+8wHF2g6mBx+mY6wU+eRaQGZJ3KH03kTm3qEIndTx5h2S25/AzNuWw6hvlDymjmD5Y10EPRV1ZCDoougDI6qZ/WOq4aC0ErFQ17yRU0T/ezJjoLjYQm+eogCcZZrRNnPu/hT/JchO/DuGLuinmxUO5CDduSmJw+BgxwXqecH5dGT3fRrm68OpbOvqsDljnc2/dpRXYBrhhP6LVpExM9hakHPRMHSsFp5hwQ0DgsH5oXYqdykhASrgY9OgOkQf9rthT70aX0wYHwG2btd/ORqyC2VzfecariqbYA9CglmfaN8aMCweJ6QYpRSEw0dpLqLkJjgBzfu2+6AhG5lHROdKFqK0LytMt/9uOU/wqOhOLC45F97VKlPrldEdonYb8aFilMu8zVD2O1EJg6qp3lf589hKGXzJNCl3iTJUbcRWAhPup48yyD+QNWQFYPPPTrJ6qVhq0gsJKVCWhjAbROT5ZFpRlSRG078TdD2QKkzCpFsukl81+G+OklWPH23lZMkFmLx0t4cUEf0pLhKMiJ5ohwYOtIz0wlkQiPKp3ODxlKzwVftvnOlIDEOKZ7hrfs8Y1qlObpVuAFF194="
  on:
    rvm: 2.4
    tags: true
