name: "Release"

on:
  push:
    tags: 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rake gem
        id: gem
      - run: bundle exec rake ronn
        id: ronn
      - uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
          github_token: ${{secrets.GITHUB_TOKEN}}

